language: java
jdk:
  - openjdk7
install: "travis_retry mvn install -Pintegration-tests -DskipTests=true -B -V -q"
script: "travis_retry mvn verify -Pintegration-tests -B -V -q"
env: MAVEN_OPTS="-XX:MaxPermSize=256m"
