language: java
jdk:
  - openjdk7
  - oraclejdk7
install: "travis_retry mvn install -Pintegration-tests -DskipTests=true -B -V"
script: "travis_retry mvn verify -Pintegration-tests -B -V"
env: MAVEN_OPTS="-XX:MaxPermSize=512m"
